### ISSUE TITLE
App Launcher component

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#322]
Create a React component based on the corresponding [SLDS component](https://core-204.lightningdesignsystem.com/components/app-launcher). 

Acceptance criteria:
- [x] The App Launcher (aka App Launcher modal) should be shown when the App Launcher icon (aka Waffle) is clicked.
- [x] See https://latest-206.lightningdesignsystem.com/components/global-navigation for the App Launcher icon
- [x] The modal should have a title. The containing app should be able to set component props in order to set up this title to support localization.
- [x] The modal should have a search box in the top-center (to the right of the title) with the placeholder text "Find an app"
- [ ] Typing into the search box should lead to a type-ahead search which should match any apps whose title (NOT description) matches the text (issue #450)
- [x] The modal should have a button titled "App Exchange" on the top right. The button should pop open a URL in a new tab. The app consuming the control should be able to set this URL.
- [ ] The app relative order must be maintained in the search results (issue #450)
- [x] Only All Apps section needs to be supported at this time
- [ ] Draggability is NOT required at this time. We will bring that in as incremental work in a separate issue since we don't have the ability to store item locations on the server at this time. (created ticket #487)
- [ ] Launcher control must have unit tests that test all the props and state (issue #431)
- [ ] Unit tests must provide >90% test coverage (issue #431)

For clarifications and details on this issue please talk to @arunjeetsingh.
